version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.34.1
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}

  shell:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "service:gluetun"
    container_name: shell
    depends_on:
      - gluetun